apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.appName }}-build
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  source:
    git:
      uri: {{ .Values.uri }}
    contextDir: {{ .Values.contextDir }}
    type: Git
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag       # Use an imagestream tag as 'FROM'. so instead of download image `again` it fetches from IS we created
        namespace: {{ .Values.namespace }}    # Which project?
        name: {{ .Values.appName }}-is:latest         # Use the imagestream created above
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.appName }}:latest"  # Use the templated value
  triggers:
  - type: ImageChange
#     imageChange:
#       from:
#         kind: ImageStreamTag
#         name: "{{ .Values.appName }}:old"
#         namespace: {{ .Values.namespace }}
