apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.appName }}-build
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.appName }}:latest"  # Use the templated value
  source:
    git:
      uri: {{ .Values.uri }}
    contextDir: {{ .Values.contextDir }}
    type: Git
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: {{ .Values.originalimage }}
        namespace: {{ .Values.namespace }}
