apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appName }}:latest
        env:
        - name: INFERENCE_ENDPOINT
          value: {{ .Values.inferenceEndpoint }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
