apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appName }}:latest
        env:
        - name: INFERENCE_ENDPOINT
          value: {{ .Values.inferenceEndpoint }}
      # Add other container settings, volume mounts, and so on as needed
