apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.originalimage }}
    importPolicy: {}
    referencePolicy:
      type: Local
#   tags:
#   - name: latest
#     from:
#       kind: DockerImage
#       name: {{ .Values.originalimage }}
#     referencePolicy:
#       type: Source