apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: name: {{ .Values.appName }}-is
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/library/python3.10.4
    referencePolicy:
      type: Source