apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: python3.10.4
    referencePolicy:
      type: Source