apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}
    deploymentconfig: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP
