lvms:
  volumeGroup: vgdatamesh

rbac:
  name: console-plugin
  namespace: Default
  roles:
    - createRole: true
      resources:
        - consoles
      scope:
        cluster: true
      apiGroups:
        - "operator.openshift.io"
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
