lvms:
  volumeGroup: vgdatamesh

rbac:
  name: console-plugin
  namespace: Default
  roles:
    - createRole: true
      resources:
        - console.operator
      scope:
        cluster: true
      apiGroups:
        - ""
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"

roleBindings:
  - createBinding: true
    scope:
      cluster: true
    subjects:
      kind: ServiceAccount
      apiGroup: ""