kind: Job
apiVersion: batch/v1
metadata:
  name: restart-console
annotations:
      argocd.argoproj.io/hook: PostSync
namespace: {{ .Values.rbacpod.namespace }}
spec:
  template:
    spec:
      containers:
      ## this image is deployed as part of VP so you can run jobs. cli and tools are 2 images that can be used. 
      ##tools has tcpdump,jq,parted,strace utilities
      - name: cli
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest 
        command:
        - /bin/bash
        - -ce
        - |
          oc delete pod -n openshift-console -l component=ui
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.rbac-pod.name }}-sa
      serviceAccountName: {{ .Values.rbac-pod.name }}-sa
      terminationGracePeriodSeconds: 400